version: "3.8"

services:
  db:
    image: mysql
    build: ./
    container_name: apw-db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apwdb
      MYSQL_USER: user129
      MYSQL_PASSWORD: user129
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
    hostname: apwapp

