version: "3.8"

services:
  db:
    container_name: web-db
    image: mysql:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apwdb
      MYSQL_USER: user129
      MYSQL_PASSWORD: user129
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./apw/web-db/conf/my.cnf:/etc/
      - ./conf/db.cnf:/etc/mysql/conf.d/db.cnf
volumes:
  db-store:

